name: Quick Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4      
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: win64

      - name: Install Ninja
        run: choco install ninja

      - name: Build OQS Provider
        run: |
          mkdir build
          cd build
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
          ninja oqsprov

      - name: Create Artifact Directory
        run: |
          mkdir artifacts
          Copy-Item "build\oqsprov\oqsprov.dll" -Destination "artifacts\"
          Copy-Item "build\examples\static_oqsprovider.exe" -Destination "artifacts\"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: oqs-provider-windows
          path: artifacts\
          retention-days: 7
